### ISSUE TITLE
Make modules generic

### ISSUE THREAD

**Issue by shubham0704** [GDGVIT/DSC_free_slots#1]
Some guidelines while adding code  to the main repository -
- [x] Move custom tests on each module into a test directory

- [x] Expose only the required functional API using classes

- [x] Code needs to be properly commented and linted

Please close this after all this is done.

Create a branch if you just want to backup your changes. Push only good code in the main branch

**Comment by paritoshM9** [comment]
Thank you for the guidelines. I have started following these and will solve the issues asap.

**Comment by paritoshM9** [comment]
A separated branch 'changes' is created , Unittesting is done for the main functions in test/test_slotfinder.py , The code is given a modular structure and abstraction is done wherever possible. The code is linted and checked using Pylint , more comments have been written.
